# Generated by Django 4.0.4 on 2022-05-31 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_alter_topic_topics'),
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='UserProfile',
        ),
    ]
