# Generated by Django 4.0.4 on 2022-06-04 08:08

import django.contrib.postgres.fields
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_suggested_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='suggested_topic',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=users.models.User.get_default, size=None),
        ),
    ]
