# Generated by Django 4.0.4 on 2022-05-18 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='right_answer',
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
