# Generated by Django 4.0.4 on 2022-05-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_questions_right_answer_delete_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='right_answer',
            field=models.IntegerField(null=True),
        ),
    ]
