# Generated by Django 4.0.4 on 2022-05-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_questions_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='attached_file',
            field=models.FileField(default='', null=True, upload_to=''),
        ),
    ]
