# Generated by Django 4.0.4 on 2022-05-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_questions_attached_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='attached_file',
            field=models.FileField(default='file.jpg', null=True, upload_to=''),
        ),
    ]
