# Generated by Django 4.0.4 on 2022-05-25 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_questions_attached_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_type',
        ),
        migrations.AddField(
            model_name='questions',
            name='question_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.questiontype'),
        ),
    ]
