# Generated by Django 4.0.4 on 2022-05-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_questiontype_remove_questions_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
