# Generated by Django 4.0.4 on 2022-05-25 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_questions_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.questiontype'),
        ),
    ]
