# Generated by Django 4.0.4 on 2022-05-31 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_alter_topic_topics'),
        ('questions', '0009_alter_questions_question_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='question_type',
        ),
        migrations.AddField(
            model_name='questions',
            name='question_topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='topics.topic'),
        ),
        migrations.DeleteModel(
            name='QuestionType',
        ),
    ]
