# Generated by Django 4.0.4 on 2022-05-31 04:31

from django.db import migrations, models
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_remove_questions_question_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=200, null=True)),
                # ('question', questions.models.NonStrippingCharField(blank=True, max_length=1, null=True)),
                ('attached_file', models.FileField(default='file.jpg', null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('right_answer', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_topic',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='questioner',
        ),
    ]
