# Generated by Django 4.0.4 on 2022-05-31 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0008_alter_answer_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0011_question_remove_questions_question_topic_and_more'),
        ('topics', '0002_alter_topic_topics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.AddField(
            model_name='question',
            name='question_topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='topics.topic'),
        ),
        migrations.AddField(
            model_name='question',
            name='questioner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
