# Generated by Django 4.0.4 on 2022-05-31 04:49

from django.db import migrations
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_alter_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=questions.models.NonStrippingCharField(blank=True, max_length=5, null=True),
        ),
    ]
