# Generated by Django 4.0.4 on 2022-05-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_alter_question_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='questionssssssssss',
            field=models.TextField(default='1', null=True),
        ),
    ]
