# Generated by Django 4.0.4 on 2022-05-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_remove_question_question_question_questionssssssssss'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='right_answer',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
