# Generated by Django 4.0.4 on 2022-05-30 16:56

import django.contrib.postgres.fields
from django.db import migrations, models
import topics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=topics.models.Topic.get_default, size=None)),
            ],
        ),
    ]
