# Generated by Django 4.0.4 on 2022-05-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topics',
            field=models.CharField(default='', max_length=100),
        ),
    ]
