# Generated by Django 4.0.4 on 2022-06-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_item', models.CharField(max_length=200)),
                ('reported_item_id', models.IntegerField()),
                ('reporter', models.CharField(max_length=200)),
                ('report_reason', models.CharField(max_length=200)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('report_count', models.IntegerField(default=0)),
            ],
        ),
    ]
