# Generated by Django 4.0.4 on 2022-05-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0002_alter_answer_attached_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay_answer',
            name='reply',
            field=models.FileField(default='file.jpg', null=True, upload_to=''),
        ),
    ]
