# Generated by Django 4.0.4 on 2022-06-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0003_alter_vote_voter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
