# Generated by Django 4.0.4 on 2022-05-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0005_alter_answer_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='replay_answer',
            name='attached_files',
            field=models.FileField(default='file.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='replay_answer',
            name='reply',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
