# Generated by Django 4.0.4 on 2022-06-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0005_alter_vote_voter'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
