# Generated by Django 4.0.4 on 2022-06-12 15:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('answer', '0006_vote_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='vote',
            field=models.ManyToManyField(related_name='vote_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
