# Generated by Django 4.0.4 on 2022-05-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0006_replay_answer_attached_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replay_answer',
            name='reply',
            field=models.TextField(null=True),
        ),
    ]
