# Generated by Django 4.0.4 on 2022-06-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0008_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_report',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
