# Generated by Django 4.0.4 on 2022-05-18 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='author',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='bookmark',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='like',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Feed',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
