# Generated by Django 4.0.4 on 2022-05-18 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='post',
        ),
    ]
