# Generated by Django 4.0.4 on 2022-06-11 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0007_alter_feed_is_dislike_alter_feed_is_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='is_dislike',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DislikedUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feed',
            name='is_like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LikedUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
