# Generated by Django 4.0.4 on 2022-06-12 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0008_alter_feed_is_dislike_alter_feed_is_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='is_dislike',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='is_like',
        ),
        migrations.AddField(
            model_name='feed',
            name='is_like',
            field=models.ManyToManyField(related_name='LikedUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
